# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - FindyTestFront

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://findytestfrontcontainerregistery.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4d38545fdd6142fa8580c8cd3f74efc9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b0a4fd58a0084ef197bf83be23fa2c8b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: findytestfrontcontainerregistery.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d38545fdd6142fa8580c8cd3f74efc9 }}/findy-front:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'FindyTestFront'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2a10322640424a879d2d162979cebdf0 }}
        images: 'findytestfrontcontainerregistery.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d38545fdd6142fa8580c8cd3f74efc9 }}/findy-front:${{ github.sha }}'